shardman:
  maps:
    db:
      selector:
        class: Shardman\Service\ShardSelector\Crc32ShardSelector
      shards:
        db1:
          bucketRanges:
            - {start: 0, end: 49999}
        db2:
          bucketRanges:
            - {start: 50000, end: 99999}

    storage:
      shards:
        s1:
          bucketRanges:
            - {start: 0, end: 99999}